### ISSUE TITLE
Build container images?

### ISSUE THREAD

**Issue by lcarva** [redhat-aqe/review-rot#77]
Hi!

There's [ralphbean/f2-reviewrot-openshift](https://github.com/ralphbean/f2-reviewrot-openshift) which has all the configuration needed for deploying review-rot in OpenShift. Although much of the configuration is specific to the Factory team, the container images are not.

There's one for [frontend](https://github.com/ralphbean/f2-reviewrot-openshift/blob/master/frontend/Dockerfile)
And another for [backend](https://github.com/ralphbean/f2-reviewrot-openshift/blob/master/backend/Dockerfile).

Frontend is just an NGINX app that serves the static files for review-rot.
Backend is a CronJob that runs periodically to generate the data.json.

We currently build these container images locally in our OpenShift project which is fine and all, but it doesn't really allow us to share it with others.

Would you be interested in having these images being built and shared in something like quay.io?

I don't mind doing the work, but I want to make sure you'd be interested before going ahead with it.

**Comment by nirzari** [comment]
@lcarva That's a wonderful idea but unfortunately, we haven't received any requests from other teams who would be interested in using it. 

Although we recently completed a project Core Review Reminder (A further extension of reviewrot) https://docs.engineering.redhat.com/pages/viewpage.action?pageId=68772128 and I am not sure if this aligns well with the new requests/enhancements. @pbortlov is the service owner for the new extension service and she might be able to comment further on that.

Just making sure the result is worth the efforts.

**Comment by pbortlov** [comment]
@lcarva @nirzari For now we are moving this project to the redhat-aqe repository on github. We will make sure that there will be at least one image for this project but the basic on in quay.io. @lcarva please schedule a meeting if you are still interested and talk about this idea.

**Comment by lcarva** [comment]
@pbortlov, I see now that there's an image in quay.io: https://quay.io/repository/pbortlov/reviewrot?tab=info 
This is great!

I'm interested in trying out the `--ignore-wip` flag, but it doesn't seem to be in the latest image yet:

```
🐚  docker run --rm -it quay.io/pbortlov/reviewrot:latest review-rot --help
/usr/lib/python2.7/site-packages/pkg_resources/__init__.py:1243: UserWarning: /.cache/Python-Eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
usage: review-rot [-h] [-c CONFIG] [-s {older,newer}] [-v VALUE]
                  [-d {y,m,d,h,min}] [-f {oneline,indented,json}]
                  [--show-last-comment [DAYS]] [--reverse]
                  [--sort {submitted,updated,commented}] [--debug]
                  [--email EMAIL [EMAIL ...]] [--irc CHANNEL [CHANNEL ...]]
                  [-k] [--cacert CACERT]

Lists pull/merge/change requests for github, gitlab, pagure, gerrit and
phabricator

optional arguments:
  -h, --help            show this help message and exit
  -c CONFIG, --config CONFIG
                        Configuration file to use
  -s {older,newer}, --state {older,newer}
                        Pull requests state 'older' or 'newer'
  -v VALUE, --value VALUE
                        Pull requests duration in terms of value(int)
  -d {y,m,d,h,min}, --duration {y,m,d,h,min}
                        Pull requests duration in terms of y=years,m=months,
                        d=days, h=hours, min=minutes
  -f {oneline,indented,json}, --format {oneline,indented,json}
                        Choose from one of a few different styles
  --show-last-comment [DAYS]
                        Show text of last comment and filter out pull requests
                        in which last comments are newer than specified number
                        of days
  --reverse             Display results with the most recent first
  --sort {submitted,updated,commented}
                        Display results sorted by the chosen event time.
                        Defaults to submitted
  --debug               Display debug logs on console
  --email EMAIL [EMAIL ...]
                        send output to list of email adresses
  --irc CHANNEL [CHANNEL ...]
                        send output to list of irc channels

SSL:
  -k, --insecure        Disable SSL certificate verification (not recommended)
  --cacert CACERT       Path to CA certificate to use for SSL certificate
                        verification

```

Should I not use that image? Or has the feature not been released yet?

**Comment by pbortlov** [comment]
Hi @lcarva,
I am sorry for the late response. The quay image is here: https://quay.io/repository/redhat-aqe/review-rot. I am not sure if it is still need

**Comment by lcarva** [comment]
Awesome! Thanks
