### ISSUE TITLE
Show date of latest comment and enable sorting by it

### ISSUE THREAD

**Issue by jbruzl** [redhat-aqe/review-rot#79]
Hello, can we show date of latest comment in Open PR overview? I would like to sort PRs by activity (last comment) instead of when PR was opened.

**Comment by pbortlov** [comment]
Hi @jbruzl, there is an option to sort by comment using --comment-sort tag. Let me know if it is helpful.

**Comment by pbortlov** [comment]
[MR#80](https://github.com/nirzari/review-rot/pull/80) by @danrodrig
