### ISSUE TITLE
IRC header confuses karma bots

### ISSUE THREAD

**Issue by lcarva** [redhat-aqe/review-rot#82]
When review-rot is configured to send IRC notifications, it starts the report like this:
```
--------------------------------------------- Code Review Reminder ---------------------------------------------
```

The dashes cause karma bots to reply with:
```
------------------------------------------- now has -26 points of karma.
```

Can we change `-` to perhaps `#`? Or better yet, maybe just don't add a header/footer at all?

**Comment by pbortlov** [comment]
[MR#84](https://github.com/nirzari/review-rot/pull/84)

**Comment by pbortlov** [comment]
The issue was fixed

**Comment by pbortlov** [comment]
#84

**Comment by pbortlov** [comment]
#84
