### ISSUE TITLE
RFE: Custom sorting formula

### ISSUE THREAD

**Issue by fivaldi** [redhat-aqe/review-rot#85]
I can imagine that different teams have different preferences on which PRs need to be taken care of first.  It would be difficult to support various sorting criteria, but I can imagine that having some crucial numbers (PR age, number of comments, days since last comment, number of code changes (patch size), project importance (by project tags/topics) etc. - all converted to some variable names), one could easily set his/her own formula for calculating sorting priority. The formula would be stored in the config file, calculated for each PR. The list of PRs would be sorted accto the calculated values.

**Comment by pbortlov** [comment]
Hello @fivaldi, 
thank you for your idea. Unfortunately this request doesn't have a big value for us. Feel free to create MR with those changes and we can test it and merge it.

Have a nice day.
